server:
  port: ${API_PORT:8080}
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:../.env[.properties],optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/trendzy}

app:
  jwt:
    public-key-path: ${JWT_PUBLIC_KEY_PATH:classpath:keys/public.pem}
  cookie:
    name: ${COOKIE_NAME:trendxee_token}
